ecolos_sylius_maker_plugin_admin_maker:
  resource: |
    alias: ecolos_sylius_maker_plugin.maker
    section: admin
    templates: SyliusAdminBundle:Crud
    redirect: update
    grid: ecolos_sylius_maker_plugin_admin_maker
    vars:
        all:
          templates:
            form: EcolosSyliusMakerPlugin:Maker:_form.html.twig
        index:
            icon: 'file image outline'
  type: sylius.resource
