ecolos_sylius_maker_plugin_list:
  path:
    de: /marken
    en: /brands
  methods: [GET]
  defaults:
    _controller: ecolos_sylius_maker_plugin.controller.maker:indexAction
    _sylius:
      template: "@EcolosSyliusMakerPlugin/Maker/index.html.twig"
      repository:
        method: findAll

ecolos_sylius_maker_plugin_show:
  path:
    de: /marken/{slug}
    en: /brands/{slug}
  methods: [GET]
  defaults:
    _controller: EcolosSyliusMakerPlugin:Maker:show
    _sylius:
      template: "@EcolosSyliusMakerPlugin/Maker/show.html.twig"
