brand_list:
  path:
    de_DE: /de_DE/marken
  methods: [GET]
  defaults:
    _controller: ecolos_sylius_brand_plugin.controller.brand:indexAction
    _sylius:
      template: "@EcolosSyliusBrandPlugin/Brand/index.html.twig"
      repository:
        method: findAll
brand_show:
  path:
    de_DE: /de_DE/marken/{slug}
  methods: [GET]
  defaults:
    _controller: ecolos_sylius_brand_plugin.controller.brand:showAction
    _sylius:
      template: "@EcolosSyliusBrandPlugin/Brand/show.html.twig"
