sylius_resource:
  resources:
    ecolos_sylius_maker_plugin.maker:
      driver: doctrine/orm
      #      controller: Ecolos\SyliusMakerPlugin\Controller\MakerController
      classes:
        model: Ecolos\SyliusMakerPlugin\Entity\Maker
        form: Ecolos\SyliusMakerPlugin\Form\Type\MakerType
      translation:
        classes:
          model: Ecolos\SyliusMakerPlugin\Entity\MakerTranslation
          form: Ecolos\SyliusMakerPlugin\Form\Type\MakerTranslationType
    ecolos_sylius_maker_plugin.maker_image:
      classes:
        model: Ecolos\SyliusMakerPlugin\Entity\MakerImage
        form: Ecolos\SyliusMakerPlugin\Form\Type\MakerImageType
