ecolos_sylius_maker_plugin_admin:
  resource: "@EcolosSyliusMakerPlugin/Resources/config/routing/admin.yaml"
  prefix: /admin

ecolos_sylius_maker_plugin_shop:
  resource: "@EcolosSyliusMakerPlugin/Resources/config/routing/shop.yaml"
  prefix: /{_locale}
