services:
  Ecolos\SyliusMakerPlugin\Command\SlugifyMakersCommand:
    public: true
    tags: ["console.command"]

  Ecolos\SyliusMakerPlugin\Repository\MakerRepository:
    tags: ['doctrine.repository_service']

  Ecolos\SyliusMakerPlugin\Repository\MakerTranslationRepository:
    tags: ['doctrine.repository_service']

  Ecolos\SyliusMakerPlugin\Service\SlugifyMakers:
    public: true
    arguments:
      - '@ecolos_sylius_maker_plugin.repository.maker'
      - '@ecolos_sylius_maker_plugin.manager.maker'

  ecolos_sylius_maker_plugin.maker.form.type:
    class: Ecolos\SyliusMakerPlugin\Form\Type\MakerType
    tags:
      - { name: form.type }
    arguments: ['%ecolos_sylius_maker_plugin.model.maker.class%', ['sylius']]

  ecolos_sylius_maker_plugin.maker_translation.form.type:
    class: Ecolos\SyliusMakerPlugin\Form\Type\MakerTranslationType
    tags:
      - { name: form.type }
    arguments: ['%ecolos_sylius_maker_plugin.model.maker_translation.class%', ['sylius']]

  ecolos_sylius_maker_plugin.form.extension.type.maker:
    class: Ecolos\SyliusMakerPlugin\Form\Extension\MakerTypeExtension
    tags:
      - { name: form.type_extension, extended_type: Ecolos\SyliusMakerPlugin\Form\Type\MakerType }

  ecolos_sylius_maker_plugin.form.extension.type.product:
    class: Ecolos\SyliusMakerPlugin\Form\Extension\ProductTypeExtension
    arguments:
      - "%ecolos_sylius_maker_plugin.model.maker.class%"
    tags:
      - { name: form.type_extension, extended_type: Sylius\Bundle\ProductBundle\Form\Type\ProductType }

  ecolos_sylius_maker_plugin.form.type.maker_choice:
    class: Ecolos\SyliusMakerPlugin\Form\Type\MakerChoiceType
    arguments:
      - "@ecolos_sylius_maker_plugin.repository.maker"
    tags:
      - { name: form.type , alias: ecolos_sylius_maker_plugin_maker_choice }

  ecolos_sylius_maker_plugin.form.type.maker_filter:
    class: Ecolos\SyliusMakerPlugin\Form\Type\Filter\MakerFilterType
    arguments: ["@sylius.context.channel.request_based", "@ecolos_sylius_maker_plugin.repository.maker"]
    tags:
      - { name: form.type , alias: ecolos_sylius_maker_plugin_maker}

  ecolos_sylius_maker_plugin.form.type.maker_image:
    class: Ecolos\SyliusMakerPlugin\Form\Type\MakerImageType
    tags:
      - { name: form.type }
    arguments: ['%ecolos_sylius_maker_plugin.model.maker_image.class%']

  ecolos_sylius_maker_plugin.grid.filter.makers:
    class: Ecolos\SyliusMakerPlugin\Grid\Filter\MakerFilter
    tags:
      - name: sylius.grid_filter
        type: makers
        form_type: Ecolos\SyliusMakerPlugin\Form\Type\Filter\MakerFilterType
    arguments: ["@ecolos_sylius_maker_plugin.repository.maker"]

  ecolos_sylius_maker_plugin.listener.admin.menu_builder:
    class: Ecolos\SyliusMakerPlugin\Menu\AdminMenuListener
    tags:
      - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAdminMenuItems }

  ecolos_sylius_maker_plugin.listener.images_upload:
    class: Sylius\Bundle\CoreBundle\EventListener\ImagesUploadListener
    parent: sylius.listener.images_upload
    autowire: true
    autoconfigure: false
    public: false
    tags:
      - { name: kernel.event_listener, event: ecolos_sylius_maker_plugin.maker.pre_create, method: uploadImages }
      - { name: kernel.event_listener, event: ecolos_sylius_maker_plugin.maker.pre_update, method: uploadImages }
