Ecolos\SyliusBrandPlugin\Entity\BrandTranslation:
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    description:
      type: string
      nullable: true
    address:
      type: string
      nullable: true
  table: ecolos_sylius_brand_plugin_brand_translation
  type: entity
