Ecolos\SyliusBrandPlugin\Entity\Brand:
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
    slug:
      type: string
      nullable: true
  oneToMany:
    images:
      targetEntity: Ecolos\SyliusBrandPlugin\Entity\BrandImage
      mappedBy: owner
      orphanRemoval: true
      cascade:
        - all
  table: ecolos_brand_brand
  type: entity
