Ecolos\SyliusMakerPlugin\Entity\MakerTranslation:
  fields:
    address:
      nullable: true
      type: string
    description:
      nullable: true
      type: string
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  table: ecolos_maker_translation
  type: entity
