Ecolos\SyliusMakerPlugin\Entity\MakerImage:
  type: entity
  table: ecolos_maker_image
  manyToOne:
    owner:
      targetEntity: Ecolos\SyliusMakerPlugin\Entity\Maker
      inversedBy: images
      joinColumn:
        name: owner_id
        referencedColumnName: id
        nullable: false
        onDelete: CASCADE
