Ecolos\SyliusMakerPlugin\Entity\Maker:
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
    slug:
      type: string
      nullable: true
  oneToMany:
    images:
      targetEntity: Ecolos\SyliusMakerPlugin\Entity\MakerImage
      mappedBy: owner
      orphanRemoval: true
      cascade:
        - all
  table: ecolos_maker_maker
  type: entity
